<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 22.02.2018
 * Time: 11:34
 */

namespace frontend\components;

use yii\base\Widget;
use frontend\models\Comments;
use yii\db\ActiveRecord;

class CommentWidgets extends Widget
{
    public $id;
    public $comments;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->id === null) {
            echo 'Параметр не передан';die();
        }
    }

    public function run()
    {
        return $this->getComments();
    }

    public function getComments()
    {
        $this->comments = Comments::find()->where(['content_id'=>$this->id])->all();
//        echo '<pre>';
//print_r($comments);
//        echo '</pre>';

        return $this->render('comments',[
            'comments' => $this->comments,
        ]);
    }
}